"use client";

import {
    Bar,
    BarChart,
    CartesianGrid,
    ResponsiveContainer,
    Tooltip,
    XAxis,
    YAxis,
} from "recharts";

import type { DashboardStats } from "@/app/actions/statistics";

type CategoryProfitChartProps = {
    data: DashboardStats;
};

const formatCurrency = (value: number) =>
    new Intl.NumberFormat("en-PK", {
        style: "currency",
        currency: "PKR",
        maximumFractionDigits: 0,
    }).format(value);

export default function CategoryProfitChart({
    data,
}: CategoryProfitChartProps) {
    const chartData = [
        {
            category: "Mobile",
            profit: data.mobile.profit,
        },
        {
            category: "Bike",
            profit: data.bike.profit,
        },
    ];

    return (
        <div className="rounded-2xl border border-border bg-card p-5 shadow-sm">
            <div>
                <h3 className="font-semibold">Profit Comparison</h3>

                <p className="mt-1 text-xs text-muted-foreground">
                    Gross profit generated by each category.
                </p>
            </div>

            <div className="mt-6 h-72 w-full">
                <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={chartData}>
                        <CartesianGrid
                            strokeDasharray="3 3"
                            className="stroke-border"
                        />

                        <XAxis
                            dataKey="category"
                            tickLine={false}
                            axisLine={false}
                            fontSize={12}
                        />

                        <YAxis
                            tickLine={false}
                            axisLine={false}
                            fontSize={12}
                        />

                        <Tooltip
                            formatter={(value) =>
                                typeof value === "number"
                                    ? formatCurrency(value)
                                    : value
                            }
                        />

                        <Bar
                            dataKey="profit"
                            name="Profit"
                            fill="currentColor"
                            className="text-emerald-600 dark:text-emerald-400"
                            radius={[6, 6, 0, 0]}
                        />
                    </BarChart>
                </ResponsiveContainer>
            </div>
        </div>
    );
}